### ISSUE TITLE
ayarlar nakliyedeki gibi kullanıcı resminin altına....

### ISSUE THREAD

**Issue by makro4242** [makro4242/Crm_V10#12]
ayarlar nakliyedeki gibi kullanıcı resminin altına olsun... ve tıklayınca kullanıcı tanıtım kartı ve yetkilendirme ve parametreler onun altında olsun yani sol menüde olmasın ..satış elemanı tanıtım kartı ve sektör tanıtım kartıda kartlar altında olsun

**Comment by sematufan** [comment]
Tamamlandı
