### ISSUE TITLE
kullanıcı sisteme login olduktan sonra...

### ISSUE THREAD

**Issue by makro4242** [makro4242/Crm_V10#16]
kullanıcı sisteme login olduktan sonra... bir popup pencere mail yedeklemenizi yaptınızmı diye sorsun altında iki cevap evet hayır... bunu tarih saat ve cevabını database ye yazalım ve Crm kullanıcısı bu kullanıcı yanıtlarını listelebilecek bir formuda oluşturalım

**Comment by sematufan** [comment]
Tamamlandı
