### ISSUE TITLE
yeni bir form açtı kullanıcı örneğin potansiyel kartı...

### ISSUE THREAD

**Issue by makro4242** [makro4242/Crm_V10#24]
yeni bir form açtı kullanıcı örneğin potansiyel kartı... oraya satış temsilcisi defaultta o kullanıcının eşleşmiş olduğu satış temsilcisi default bilgi gelsin...bunuda kullanıcı bazlı parametreye bağlayalım

**Comment by sematufan** [comment]
tamamlndı
