### ISSUE TITLE
ayarlara tıklayınca sql connection bilgileri gelsin ve ayarlanabilsin

### ISSUE THREAD

**Issue by makro4242** [makro4242/Crm_V10#9]
ayarların altında sql server connection bilgileri için bağlantı formu oluşturulacak ayarlar ı yukarıdaki kullanıcı kelle resminin altına alalımmı bunu konuşalım nakliye ile ikisindede ayarlar aynı yapıya bürüne cek

**Comment by sematufan** [comment]
tamamlandı.
